### ISSUE TITLE
Extreme slope values on smoothing

### ISSUE THREAD

**Issue by jonathancolledge** [brenzy/gpx-smoother#3]
[Winnats Pass Totally redone flat 5.txt](https://github.com/brenzy/gpx-smoother/files/4078970/Winnats.Pass.Totally.redone.flat.5.txt)

Can you please tell me why when smoothing the attached file (rename to gpx), it results in extreme slope values?

**Comment by brenzy** [comment]
The smoother is working on the elevation rather than on the slope.  It is a naive algorithm, and does not take into account that the distance between the points is variable.  As the elevation changes between two points that are spaced closely together these spikes can happen.  

The purpose of this app is to make gpx tracks rideable.  You can get rid of the spikes by using the `Set Slope Range` and/or `Flatten Values` buttons.  

I have been looking into some more sophisticated algorithms, but I'm still on the fence as to whether I want to add complexity to the app when it works for my purposes.

**Comment by brenzy** [comment]
@jonathancolledge I have been getting a lot of questions on the smoother lately since there are a lot more people riding indoors.  I decided to throw a few more algorithms at it, to see if I could get better results.  

Using a Kalman filter seems to get rid of the spikes in the slope in your file.  The newest version of my smoother is served up here: https://www.potter.ca/Biking/smoother-beta/index.html#/ and the repo is here: https://github.com/brenzy/gpx-smoother-vue.

Using flatten values also has a similar effect as the Kalman filter (as mentioned previously), and I have bumped down the default value because it seems to work for more sample files.
